import { vi, describe, it, expect, beforeEach } from 'vitest'
import { updateSprintStatus } from './sprint-status-writer.js'

const { mockReadFile, mockWriteFile } = vi.hoisted(() => ({
  mockReadFile: vi.fn(),
  mockWriteFile: vi.fn().mockResolvedValue(undefined),
}))
vi.mock('node:fs/promises', () => ({
  readFile: mockReadFile,
  writeFile: mockWriteFile,
}))

const SAMPLE_YAML = `# Sprint Status
# Generated by sprint planning

development_status:
  # Epic 1: Foundation
  1-1-project-setup: done
  1-2-frontend-project-initialization: backlog
  1-3-backend-api-setup: in-progress
  # Epic 2: Features
  2-1-user-authentication: backlog
  1-20-some-other-story: backlog
`

describe('updateSprintStatus', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('replaces status for matching story key', async () => {
    mockReadFile.mockResolvedValue(SAMPLE_YAML)
    await updateSprintStatus('/impl', '1-2', 'done')
    expect(mockWriteFile).toHaveBeenCalledOnce()
    const written = mockWriteFile.mock.calls[0][1] as string
    expect(written).toContain('1-2-frontend-project-initialization: done')
    // Other entries unchanged
    expect(written).toContain('1-1-project-setup: done')
    expect(written).toContain('1-3-backend-api-setup: in-progress')
  })

  it('preserves comments and other entries', async () => {
    mockReadFile.mockResolvedValue(SAMPLE_YAML)
    await updateSprintStatus('/impl', '1-3', 'done')
    const written = mockWriteFile.mock.calls[0][1] as string
    expect(written).toContain('# Sprint Status')
    expect(written).toContain('# Epic 1: Foundation')
    expect(written).toContain('1-1-project-setup: done')
    expect(written).toContain('1-2-frontend-project-initialization: backlog')
    expect(written).toContain('1-3-backend-api-setup: done')
  })

  it('no-op when story key not found', async () => {
    mockReadFile.mockResolvedValue(SAMPLE_YAML)
    await updateSprintStatus('/impl', '9-9', 'done')
    expect(mockWriteFile).not.toHaveBeenCalled()
  })

  it('no-op when file not found', async () => {
    mockReadFile.mockRejectedValue(new Error('ENOENT'))
    await updateSprintStatus('/impl', '1-1', 'done')
    expect(mockWriteFile).not.toHaveBeenCalled()
  })

  it('does not match 1-2 against 1-20-some-other-story', async () => {
    mockReadFile.mockResolvedValue(SAMPLE_YAML)
    await updateSprintStatus('/impl', '1-2', 'done')
    const written = mockWriteFile.mock.calls[0][1] as string
    // 1-20 should remain unchanged
    expect(written).toContain('1-20-some-other-story: backlog')
  })

  it('reads from implementationPath/sprint-status.yaml', async () => {
    mockReadFile.mockResolvedValue(SAMPLE_YAML)
    await updateSprintStatus('/my/impl/path', '1-1', 'done')
    expect(mockReadFile).toHaveBeenCalledWith('/my/impl/path/sprint-status.yaml', 'utf-8')
  })
})
